AURORA_INVENTORY.PUBLICUSE DATABASE AURORA_INVENTORY;
USE SCHEMA MAIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DYNAMIC TABLE DAILY_STOCK_CLEAN
TARGET_LAG = '5 minutes'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    DATE,
    LOCATION_NAME,
    ITEM_NAME,
    OPENING_STOCK,
    RECEIVED,
    ISSUED,
    CLOSING_STOCK,
    LEAD_TIME_DAYS,
    GREATEST(OPENING_STOCK + RECEIVED - CLOSING_STOCK, 0) AS DAILY_CONSUMPTION
FROM DAILY_STOCK;


CREATE OR REPLACE DYNAMIC TABLE STOCK_HEALTH
TARGET_LAG = '5 minutes'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    DATE,
    LOCATION_NAME,
    ITEM_NAME,
    DAILY_CONSUMPTION,
    CASE 
        WHEN DAILY_CONSUMPTION = 0 THEN 999
        ELSE ROUND(CLOSING_STOCK / DAILY_CONSUMPTION, 2)
    END AS DAYS_OF_COVER,
    CLOSING_STOCK,
    CASE
        WHEN CLOSING_STOCK <= 5 THEN 'CRITICAL'
        WHEN CLOSING_STOCK <= 15 THEN 'WARNING'
        ELSE 'OK'
    END AS RISK_LEVEL
FROM DAILY_STOCK_CLEAN;

CREATE OR REPLACE DYNAMIC TABLE STOCK_ALERTS
TARGET_LAG = '5 minutes'
WAREHOUSE = COMPUTE_WH
AS
SELECT *
FROM STOCK_HEALTH
WHERE RISK_LEVEL IN ('CRITICAL','WARNING');

